services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./pages:/app/pages
    environment:
      - FLASK_ENV=production
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ctf_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql